"""
Watchlist stocks for the /watchlist command.

Each entry is a dict with keys:
    code   — Futu-style stock code, e.g. "HK.00700"
    name   — Short company name
    source — How the stock was added (e.g. "manual", "scanner")

Add entries here to have them appear in the /watchlist Excel report.
"""

WATCHLIST_STOCKS: list[dict] = [
    {"code": "HK.00426", "name": "ONE MEDIA GROUP", "source": "Unkown Trading App"},
    {"code": "HK.02502", "name": "JINYUAN HCHEM", "source": "ABCI"},
    {"code": "HK.03816", "name": "KFM KINGDOM", "source": "Unkown Trading App"},
    {"code": "HK.01229", "name": "NAN NAN RES", "source": "ABCI"},
    {"code": "HK.01172", "name": "MAGNUSCONCORDIA", "source": "Futu"},
    {"code": "HK.03759", "name": "PHARMARON", "source": "Futu"},
    {"code": "HK.01171", "name": "YANKUANG ENERGY", "source": "ABCI"},
    {"code": "HK.02159", "name": "MEDIWELCOME", "source": "ABCI"},
    {"code": "HK.00401", "name": "WANJIA GROUP", "source": "ABCI"},
    {"code": "HK.06038", "name": "G & M HLDGS", "source": "ABCI"},
    {"code": "HK.02618", "name": "JD LOGISTICS", "source": "Futu"},
    {"code": "HK.01581", "name": "PROGRESSIVE P", "source": "ABCI"},
    {"code": "HK.00883", "name": "CNOOC", "source": "ABCI"},
    {"code": "HK.01536", "name": "YUK WING GP", "source": "ABCI"},
    {"code": "HK.02250", "name": "B.DUCK SEMK", "source": "ABCI"},
    {"code": "HK.01690", "name": "LAP KEI ENGRG", "source": "ABCI"},
    {"code": "HK.00037", "name": "FE HOTELS", "source": "Unkown Trading App"},
    {"code": "HK.00968", "name": "XINYI SOLAR", "source": "ABCI"},
    {"code": "HK.00064", "name": "GET NICE", "source": "ABCI"},
    {"code": "HK.00861", "name": "DC HOLDINGS", "source": "ABCI"},
    {"code": "HK.01985", "name": "MICROWARE", "source": "ABCI"},
    {"code": "HK.02197", "name": "CLOVER BIO-B", "source": "ABCI"},
    {"code": "HK.01314", "name": "TSUI WAH HLDG", "source": "ABCI"},
    {"code": "HK.01610", "name": "COFCO JOYCOME", "source": "ABCI"},
    {"code": "HK.02158", "name": "YIDU TECH", "source": "Futu"},
    {"code": "HK.06823", "name": "HKT-SS", "source": "ABCI"},
    {"code": "HK.06049", "name": "POLY PPT SER", "source": "ABCI"},
    {"code": "HK.00836", "name": "CHINA RES POWER", "source": "Futu"},
    {"code": "HK.01745", "name": "LVJI TECH", "source": "ABCI"},
    {"code": "HK.01250", "name": "SDHS NEW ENERGY", "source": "ABCI"},
    {"code": "HK.02425", "name": "AUSTASIA GROUP", "source": "ABCI"},
    {"code": "HK.02845", "name": "Global X China Electric Vehicle and Battery ETF", "source": "ABCI"},
    {"code": "HK.00300", "name": "MIDEA GROUP", "source": "ABCI"},
    {"code": "HK.02460", "name": "CR BEVERAGE", "source": "Futu"},
    {"code": "HK.06690", "name": "HAIER SMARTHOME", "source": "ABCI"},
    {"code": "HK.06060", "name": "ZA ONLINE", "source": "Futu"},
    {"code": "HK.01873", "name": "VIVA BIOTECH", "source": "ABCI"},
    {"code": "HK.01502", "name": "FIN STREET PPT", "source": "ABCI"},
    {"code": "HK.06618", "name": "JD HEALTH", "source": "ABCI"},
    {"code": "HK.00816", "name": "JINMAO SERVICES", "source": "ABCI"},
    {"code": "HK.02196", "name": "FOSUN PHARMA", "source": "ABCI"},
    {"code": "HK.02202", "name": "CHINA VANKE", "source": "ABCI"},
    {"code": "HK.00638", "name": "FIBOCOM", "source": "ABCI"},
    {"code": "HK.03690", "name": "MEITUAN-W", "source": "ABCI"},
    {"code": "HK.01276", "name": "HENGRUI PHARMA", "source": "Futu"},
    {"code": "HK.00700", "name": "TENCENT", "source": "ABCI"},
    {"code": "HK.00732", "name": "TRULY INT'L", "source": "ABCI"},
    {"code": "HK.01833", "name": "PA GOODDOCTOR", "source": "ABCI"},
    {"code": "HK.00241", "name": "ALI HEALTH", "source": "Futu"},
    {"code": "HK.00082", "name": "CRAZY SPORTS", "source": "ABCI"},
    {"code": "HK.00823", "name": "LINK REIT", "source": "ABCI"},
    {"code": "HK.01413", "name": "FEG HOLDINGS", "source": "ABCI"},
    {"code": "HK.00683", "name": "KERRY PPT", "source": "ABCI"},
    {"code": "HK.01321", "name": "CHINA NEWCITY", "source": "ABCI"},
    {"code": "HK.00248", "name": "HKC INT'L-NEW", "source": "ABCI"},
    {"code": "HK.01880", "name": "CTG DUTY-FREE", "source": "ABCI"},
    {"code": "HK.00853", "name": "MICROPORT", "source": "ABCI"},
    {"code": "HK.02160", "name": "MP CARDIO-B-NEW", "source": "ABCI"},
    {"code": "HK.02013", "name": "WEIMOB INC", "source": "Futu"},
    {"code": "HK.00688", "name": "CHINA OVERSEAS", "source": "ABCI"},
    {"code": "HK.01299", "name": "AIA", "source": "ABCI"},
    {"code": "HK.00045", "name": "HK&S HOTELS", "source": "ABCI"},
    {"code": "HK.01971", "name": "RSUN SER", "source": "ABCI"},
    {"code": "HK.02580", "name": "AUX ELECTRIC", "source": "ABCI"},
    {"code": "HK.02259", "name": "ZIJIN GOLD INTL", "source": "Futu"},
    {"code": "HK.03986", "name": "GIGADEVICE", "source": "ABCI"},
    {"code": "HK.00689", "name": "EPI (HOLDINGS)", "source": "ABCI"},
    {"code": "HK.03800", "name": "GCL TECH", "source": "ABCI"},
    {"code": "HK.06616", "name": "GLOBAL NEW MAT", "source": "ABCI"},
    {"code": "HK.01114", "name": "BRILLIANCE CHI", "source": "Futu"},
    {"code": "HK.00100", "name": "MINIMAX-WP", "source": "Futu"},
    {"code": "HK.03913", "name": "KWG LIVING", "source": "ABCI"},
    {"code": "HK.06687", "name": "JST GROUP", "source": "ABCI"},
    {"code": "HK.00020", "name": "SENSETIME-W", "source": "Futu"},
    {"code": "HK.00104", "name": "ASIA COMM HOLD", "source": "Unkown Trading App"},
    {"code": "HK.00183", "name": "WINFULL GP", "source": "Unkown Trading App"},
    {"code": "HK.00280", "name": "KING FOOK HOLD", "source": "ABCI"},
    {"code": "HK.00286", "name": "AIDIGONG", "source": "ABCI"},
    {"code": "HK.00251", "name": "SEA HOLDINGS", "source": "ABCI"},
    {"code": "HK.00844", "name": "GREATIME INTL", "source": "ABCI"},
    {"code": "HK.00859", "name": "ZHONGCHANG INTL", "source": "Unkown Trading App"},
    {"code": "HK.00941", "name": "CHINA MOBILE", "source": "ABCI"},
    {"code": "HK.01002", "name": "V.S. INT'L", "source": "Unkown Trading App"},
    {"code": "HK.01049", "name": "CELESTIAL ASIA", "source": "ABCI"},
    {"code": "HK.01064", "name": "ZHONG HUA INT'L", "source": "ABCI"},
    {"code": "HK.01406", "name": "CLARITY MEDICAL", "source": "Unkown Trading App"},
    {"code": "HK.01452", "name": "DENOX ENV", "source": "ABCI"},
    {"code": "HK.01516", "name": "SUNAC SERVICES", "source": "Futu"},
    {"code": "HK.01591", "name": "SHUN WO GROUP", "source": "ABCI"},
    {"code": "HK.01633", "name": "SHEUNG YUE GP", "source": "ABCI"},
    {"code": "HK.01922", "name": "RUISEN LIFE SER", "source": "ABCI"},
    {"code": "HK.01952", "name": "EVEREST MED", "source": "ABCI"},
    {"code": "HK.02660", "name": "ZENGAME", "source": "Futu"},
    {"code": "HK.02669", "name": "CHINA OVS PPT", "source": "ABCI"},
    {"code": "HK.02882", "name": "3DG HOLDINGS", "source": "Futu"},
    {"code": "HK.03319", "name": "A-LIVING", "source": "ABCI"},
    {"code": "HK.03662", "name": "STARJOY W&T", "source": "ABCI"},
    {"code": "HK.03822", "name": "SAM WOO CONS", "source": "ABCI"},
    {"code": "HK.03997", "name": "TSO", "source": "ABCI"},
]
